### ISSUE TITLE
Kunena Latest - Bad value follow for attribute rel on element a:

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Addons#153]
If u chose Show categories in Category Filter in Basic Options, the Markup Validation Service said: Bad value follow for attribute rel on element a: The string follow is not a registered keyword or absolute URL.

**Comment by schmatzler** [comment]
rel=follow is defined in lib/kunena.link.class.php and various files of the blue_eagle template.

The problem is that rel=follow never existed. If we want to specify that a link has to be followed, we just omit rel=nofollow and do nothing at all.

Imho the correct solution would be to remove all references to rel=follow.

**Comment by severdia** [comment]
There is no such thing as `rel="follow"` because that's the default. There is only `rel="nofollow"`. Please remove the `rel="follow"` attributes from the Kunena Latest Module.

**Comment by 810** [comment]
fixed on K5.0.1
